[package]
name = "pagetop-website"
version = "0.0.6"
edition = "2021"

authors = [
    "Manuel Cillero <manuel@cillero.es>"
]
description = """\
    PageTop website.\
"""
homepage = "https://pagetop.cillero.es"
repository = "https://github.com/manuelcillero/pagetop-website"
license = "Apache-2.0 OR MIT"

[dependencies]
actix-web = "4"
static-files = "0.2.3"
pagetop = { version = "0.0", path = "../PageTop/pagetop" }
pagetop-bootsier = { version = "0.0", path = "../PageTop/pagetop-bootsier" }
pagetop-homedemo = { version = "0.0", path = "../PageTop/pagetop-homedemo" }
pagetop-mdbook = { version = "0.0", path = "../pagetop-mdbook" }

[build-dependencies]
pagetop-build = { version = "0.0", path = "../PageTop/pagetop-build" }
pagetop-mdbook = { version = "0.0", path = "../pagetop-mdbook" }
