[app]
name = "PageTop"
description = "An opinionated Rust web framework to build secure and modular web solutions."
#theme = "Basic"
#theme = "Chassis"
theme = "Inception"
#theme = "Bootsier"

[log]
rolling = "Daily"
